#!/usr/bin/env python3
"""Render Trevino Figure 3E public-matrix motif enrichment dotplot.

Consumes the motif-enrichment TSV generated by ``wave5_figure3_motif_enrichment.R``.
The preferred input for the current public-matrix lane is the Figure 3C
``derived_k5_cluster`` run, so the panel is aligned with the k=5 heatmap rather
than the local Table S3B k10 labels.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def save_triple(fig: plt.Figure, out_dir: Path, stem: str) -> dict[str, str]:
    paths = {
        "png": out_dir / f"{stem}.png",
        "svg": out_dir / f"{stem}.svg",
        "pdf": out_dir / f"{stem}.pdf",
    }
    fig.savefig(paths["png"], dpi=300, bbox_inches="tight")
    fig.savefig(paths["svg"], bbox_inches="tight")
    fig.savefig(paths["pdf"], dpi=300, bbox_inches="tight")
    plt.close(fig)
    return {f"{k}_path": str(v) for k, v in paths.items()} | {
        f"{k}_sha256": sha256_file(v) for k, v in paths.items()
    }


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--motif-enrichment", required=True, type=Path)
    p.add_argument("--readiness-json", required=True, type=Path)
    p.add_argument("--out-dir", required=True, type=Path)
    p.add_argument("--universe", default="all_consensus_peaks")
    p.add_argument("--top-n-per-cluster", type=int, default=10)
    args = p.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    enrich = pd.read_csv(args.motif_enrichment, sep="\t")
    readiness = json.loads(args.readiness_json.read_text())
    required = {"universe", "group", "motif_name", "matches", "draws", "p_adj_bonferroni", "log2_fold_enrichment"}
    missing = sorted(required.difference(enrich.columns))
    if missing:
        raise ValueError(f"Motif enrichment TSV missing columns: {missing}")
    sub = enrich[(enrich["universe"] == args.universe) & (enrich["log2_fold_enrichment"] > 0)].copy()
    if sub.empty:
        raise ValueError(f"No positive motif enrichment rows for universe={args.universe}")
    sub["neg_log10_p_adj"] = -np.log10(np.maximum(sub["p_adj_bonferroni"].to_numpy(float), np.finfo(float).tiny))
    sub = sub.sort_values(["group", "p_adj_bonferroni", "enrichment_p", "motif_name"])
    top = sub.groupby("group", observed=True).head(args.top_n_per_cluster).copy()
    top_tsv = args.out_dir / "figure3e_top_motifs_by_cluster.tsv"
    top.to_csv(top_tsv, sep="\t", index=False)

    cluster_order = sorted(top["group"].astype(str).unique())
    motif_order = list(dict.fromkeys(top["motif_name"].astype(str).tolist()))
    plot_df = top.copy()
    x_map = {c: i for i, c in enumerate(cluster_order)}
    y_map = {m: i for i, m in enumerate(reversed(motif_order))}
    plot_df["x"] = plot_df["group"].astype(str).map(x_map)
    plot_df["y"] = plot_df["motif_name"].astype(str).map(y_map)
    plot_df["size"] = 20 + 18 * np.minimum(plot_df["neg_log10_p_adj"], 12)

    fig_h = max(5.0, 0.18 * len(motif_order))
    fig, ax = plt.subplots(figsize=(7.5, fig_h))
    sc = ax.scatter(
        plot_df["x"],
        plot_df["y"],
        s=plot_df["size"],
        c=plot_df["log2_fold_enrichment"],
        cmap="magma",
        edgecolor="black",
        linewidth=0.25,
    )
    ax.set_xticks(range(len(cluster_order)))
    ax.set_xticklabels(cluster_order)
    ax.set_yticks(range(len(motif_order)))
    ax.set_yticklabels(list(reversed(motif_order)), fontsize=7)
    ax.set_xlabel("Figure 3C derived k=5 interaction cluster")
    ax.set_ylabel("motif")
    ax.set_title("Trevino Fig. 3E public-matrix motif enrichment")
    cbar = fig.colorbar(sc, ax=ax, shrink=0.75)
    cbar.set_label("log2 fold enrichment")
    ax.grid(axis="x", alpha=0.2)
    figure_outputs = {"motif_dotplot": save_triple(fig, args.out_dir, "figure3e_motif_enrichment_dotplot")}

    significant = sub[sub["p_adj_bonferroni"] <= 0.05]
    summary = {
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "status": "GENERATED_PUBLIC_MATRIX_DERIVED_K5_MOTIF_ENRICHMENT",
        "truth_boundary": (
            "Motif enrichment diagnostic over Figure 3C derived-k5 linked peaks using local author motif match matrix. "
            "This is not exact LOLA/JASPAR/topGO environment parity and does not resolve unavailable author original heatmap object."
        ),
        "motif_enrichment": str(args.motif_enrichment),
        "readiness_json": str(args.readiness_json),
        "out_dir": str(args.out_dir),
        "parameters": {"universe": args.universe, "top_n_per_cluster": args.top_n_per_cluster},
        "readiness": readiness,
        "input_rows": int(len(enrich)),
        "positive_rows_in_universe": int(len(sub)),
        "significant_positive_rows_bonferroni_0_05": int(len(significant)),
        "groups": cluster_order,
        "top_motifs_by_cluster": {
            group: df[["motif_name", "matches", "draws", "log2_fold_enrichment", "p_adj_bonferroni"]]
            .head(args.top_n_per_cluster)
            .to_dict("records")
            for group, df in sub.groupby("group", observed=True)
        },
        "outputs": {"top_tsv": str(top_tsv), "figure_outputs": figure_outputs},
        "checks": {
            "readiness_all_table_rows_mapped": bool(readiness.get("all_table_rows_mapped")),
            "cluster_count_matches_derived_k5": int(readiness.get("cluster_count", 0)) == 5,
            "positive_rows_present": len(sub) > 0,
            "significant_positive_rows_present": len(significant) > 0,
            "all_groups_have_top_rows": all((top["group"].astype(str) == group).any() for group in cluster_order),
        },
    }
    summary_path = args.out_dir / "figure3e_motif_enrichment_summary.json"
    summary_path.write_text(json.dumps(summary, indent=2, ensure_ascii=False) + "\n")
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
